fix merge conflict

diff --git a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/init-magicdns-proxies/run b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/init-magicdns-proxies/run
--- a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/init-magicdns-proxies/run
+++ b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/init-magicdns-proxies/run
@@ -13,12 +13,15 @@ readonly DNSMASQ_BLACK_WHITE_LIST_LOCATION="/etc/dnsmasq-black-white-list"
 declare login_server="${DEFAULT_LOGIN_SERVER}"
 declare -a black_white_list=()
 
-# We have to be able to determine login_server from this address
-if ! login_server=$(awk -F[/:] '{print $4}' <<<$(bashio::config "login_server")) || \
-  ! bashio::var.has_value "${login_server}"
-then
-  bashio::log.error "Determining host name from '$(bashio::config "login_server")' has failed"
-  bashio::exit.nok
+# Get login_server if configured
+if bashio::config.has_value "login_server"; then
+  # We have to be able to determine login_server from this address
+  if ! login_server=$(awk -F[/:] '{print $4}' <<<$(bashio::config "login_server")) || \
+    ! bashio::var.has_value "${login_server}"
+  then
+    bashio::log.error "Determining host name from '$(bashio::config "login_server")' has failed"
+    bashio::exit.nok
+  fi
 fi
 black_white_list+=(${login_server})
 
