warn, when there's no default interface

diff --git a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/forwarding/run b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/forwarding/run
--- a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/forwarding/run
+++ b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/forwarding/run
@@ -75,17 +75,22 @@ function setup_forwarding() {
   fi
 }
 
-# Tailscale's IP addresses
-if ! from_address_ipv4=$(/opt/tailscale ip -4); then
-  bashio::log.warning "Failed to retrieve Tailscale's IPv4 address"
-fi
-if ! from_address_ipv6=$(/opt/tailscale ip -6); then
-  bashio::log.warning "Failed to retrieve Tailscale's IPv6 address"
-fi
+if ! bashio::api.supervisor GET "/network/interface/default/info" false > /dev/null; then
+  bashio::log.warning \
+    "The host has no primary (default) interface, can't forward incoming tailnet connections to the host"
+else
+  # Tailscale's IP addresses
+  if ! from_address_ipv4=$(/opt/tailscale ip -4); then
+    bashio::log.warning "Failed to retrieve Tailscale's IPv4 address"
+  fi
+  if ! from_address_ipv6=$(/opt/tailscale ip -6); then
+    bashio::log.warning "Failed to retrieve Tailscale's IPv6 address"
+  fi
 
-# Host's IP addresses
-to_address_ipv4=$(get_host_address "ipv4")
-to_address_ipv6=$(get_host_address "ipv6")
+  # Host's IP addresses
+  to_address_ipv4=$(get_host_address "ipv4")
+  to_address_ipv6=$(get_host_address "ipv6")
 
-setup_forwarding "iptables" "IPv4" "${from_address_ipv4}" "32" "${to_address_ipv4}"
-setup_forwarding "ip6tables" "IPv6" "${from_address_ipv6}" "128" "${to_address_ipv6}"
+  setup_forwarding "iptables" "IPv4" "${from_address_ipv4}" "32" "${to_address_ipv4}"
+  setup_forwarding "ip6tables" "IPv6" "${from_address_ipv6}" "128" "${to_address_ipv6}"
+fi
