Proxy and Funnel are disabled by default (#273)

diff --git a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/run b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/run
--- a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/run
+++ b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/run
@@ -7,31 +7,39 @@
 
 declare domain
 
-# Check if Tailscale HTTPS is enabled
-if ! /opt/tailscale status --self=true --peers=false --json \
-  | jq -rce '.Self.CapMap | has("https")' > /dev/null;
-then
-  bashio::log.notice "Tailscale's HTTPS support is disabled, therefore add-on's Tailscale Proxy functionality is disabled"
-  bashio::exit.ok
-fi
-
-domain=$(/opt/tailscale status --self=true --peers=false --json | jq -rc ".CertDomains[0]")
-
-# Checking if SSL is used
-if bashio::var.true "$(bashio::core.ssl)"; then
-  bashio::log.error "Tailscale's HTTPS support is enabled, but Home Assistant is not accessible through plain HTTP connection"
+# Tailscale serve and funnel configuration is persistent between restarts
+# Disable previously configured tailscale serve functionality with deleting the tailscale serve configuration
+if ! /opt/tailscale serve reset; then
+  bashio::log.error "Unable to reset Tailscale Proxy settings"
   bashio::exit.nok
 fi
 
-# Set up proxy
-# Note: Configuration is persistent between reboots, though configuring the same value won't cause duplicate entries,
-#       but will overwite previous entry if core.port has been changed
-# Note: If a tailnet node is renamed, there will be deprecated entries in status json under .Web.<different-domain:443>,
-#       those can't be removed, no command for that situation currently
-if ! /opt/tailscale serve https:443 / "http://127.0.0.1:$(bashio::core.port)"; then
-  bashio::log.error "Unable to configure Tailscale Proxy"
-  bashio::exit.nok
+# Enable proxy service only when it has been explicitly enabled
+if bashio::config.true 'proxy'; then
+
+  # Check if Tailscale HTTPS is enabled
+  if ! /opt/tailscale status --self=true --peers=false --json \
+    | jq -rce '.Self.CapMap | has("https")' > /dev/null;
+  then
+    bashio::log.error "Tailscale's HTTPS support is disabled"
+    bashio::exit.nok
+  fi
+
+  domain=$(/opt/tailscale status --self=true --peers=false --json | jq -rc ".CertDomains[0]")
+
+  # Checking if SSL is used
+  if bashio::var.true "$(bashio::core.ssl)"; then
+    bashio::log.error "Tailscale's HTTPS support is enabled, but Home Assistant is not accessible through plain HTTP connection"
+    bashio::exit.nok
+  fi
+
+  # Set up proxy
+  if ! /opt/tailscale serve https:443 / "http://127.0.0.1:$(bashio::core.port)"; then
+    bashio::log.error "Unable to configure Tailscale Proxy"
+    bashio::exit.nok
+  fi
+  bashio::log.info "Tailscale Proxy is enabled:"
+  bashio::log.info "  Your Home Assistant instance is available within your Tailnet VPN at"
+  bashio::log.info "  https://${domain}"
+
 fi
-bashio::log.info "Tailscale Proxy is enabled:"
-bashio::log.info "  Your Home Assistant instance is available within your Tailnet VPN at"
-bashio::log.info "  https://${domain}"
