Skip DHCP lease renewal in subnet protection service if nothing has changed (#505)

diff --git a/tailscale/rootfs/etc/NetworkManager/dispatcher.d/protect-subnets b/tailscale/rootfs/etc/NetworkManager/dispatcher.d/protect-subnets
--- a/tailscale/rootfs/etc/NetworkManager/dispatcher.d/protect-subnets
+++ b/tailscale/rootfs/etc/NetworkManager/dispatcher.d/protect-subnets
@@ -2,15 +2,30 @@
 # shellcheck shell=bash
 # The shebang 'with-contenv-merge' above is identical with 'with-contenv', but doesn't clear the current environment containing the dispatcher variables
 
+function halt-add-on() {
+  bashio::log.error "Failed to protect subnet routes. Halting add-on to prevent network loss."
+  echo -n 1 > /run/s6-linux-init-container-results/exitcode
+  exec /run/s6/basedir/bin/halt
+}
+
 case "${NM_DISPATCHER_ACTION}" in
-  up|down|dhcp4-change|dhcp6-change)
+  up|down)
     bashio::log.info "Handling Network Manager action ${DEVICE_IP_IFACE-} ${NM_DISPATCHER_ACTION}"
     unprotect-subnet-routes
     if ! protect-subnet-routes; then
       # Better stop add-on than risking losing all network connections
-      bashio::log.error "Failed to protect subnet routes. Halting add-on to prevent network loss."
-      echo -n 1 > /run/s6-linux-init-container-results/exitcode
-      exec /run/s6/basedir/bin/halt
+      halt-add-on
+    fi
+    ;;
+  dhcp4-change|dhcp6-change)
+    # Do anything only when the addresses are really changed
+    if [[ "$(unprotect-subnet-routes test)" != "$(protect-subnet-routes test)" ]]; then
+      bashio::log.info "Handling Network Manager action ${DEVICE_IP_IFACE-} ${NM_DISPATCHER_ACTION}"
+      unprotect-subnet-routes
+      if ! protect-subnet-routes tested; then
+        # Better stop add-on than risking losing all network connections
+        halt-add-on
+      fi
     fi
     ;;
   connectivity-change)
