execute conditionally, fail silently

diff --git a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
--- a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
+++ b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
@@ -17,15 +17,16 @@ declare keyexpiry
 # Based on: https://tailscale.com/kb/1320/performance-best-practices#linux-optimizations-for-subnet-routers-and-exit-nodes
 # Note: Changes made via ethtool are not persistent and will be lost after the machine shuts down
 # Note: Executing it before "tailscale up" to avoid warning messages
-for interface in $( \
-  { ip -4 route show 0/0; ip -6 route show ::/0; } \
-  | { grep -E '^default\svia\s\S+\sdev\s\S+' || true ;} \
-  | cut -f5 -d' ' \
-  | sort -u)
-do
+# Note: Everything fails silently, we do a best effort only.
+if interface=$( \
+  curl -sf --unix-socket /var/run/tailscale/tailscaled.sock http://local-tailscaled.sock/localapi/v0/check-udp-gro-forwarding \
+  | jq -rc '.Warning' \
+  | sed -nr 's/^UDP GRO forwarding is suboptimally configured on (\S+),.*$/\1/p') \
+  && bashio::var.has_value "${interface}";
+then
   bashio::log.info "Allow UDP GRO for forwarding on ${interface}"
-  ethtool -K "${interface}" rx-udp-gro-forwarding on rx-gro-list off
-done
+  ethtool -K "${interface}" rx-udp-gro-forwarding on rx-gro-list off &> /dev/null || true
+fi
 
 # Default options
 options+=(--hostname "$(bashio::info.hostname)")
