remove duplicate status checks from dependent s6 services

diff --git a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
--- a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
+++ b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
@@ -92,4 +92,17 @@ do
   sleep 2
 done
 
-/opt/tailscale up "${options[@]}"
+# Start Tailscale
+if ! /opt/tailscale up "${options[@]}"; then
+  bashio::log.error "Unable to start up Tailscale"
+  bashio::exit.nok
+fi
+
+# Wait for the network to be available and logged in
+while ! /opt/tailscale status --json --peers=false --self=false \
+  | jq --exit-status '.BackendState == "Running"' > /dev/null
+do
+  sleep 2
+done
+
+bashio::log.info "Tailscale is running"
