Failsafe enabling of UDP GRO for forwarding (#370)

diff --git a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
--- a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
+++ b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
@@ -13,20 +13,6 @@ declare login_server
 declare tags
 declare keyexpiry
 
-# Linux optimizations for subnet routers and exit nodes
-# Based on: https://tailscale.com/kb/1320/performance-best-practices#linux-optimizations-for-subnet-routers-and-exit-nodes
-# Note: Changes made via ethtool are not persistent and will be lost after the machine shuts down
-# Note: Executing it before "tailscale up" to avoid warning messages
-for interface in $( \
-  { ip -4 route show 0/0; ip -6 route show ::/0; } \
-  | { grep -E '^default\svia\s\S+\sdev\s\S+' || true ;} \
-  | cut -f5 -d' ' \
-  | sort -u)
-do
-  bashio::log.info "Allow UDP GRO for forwarding on ${interface}"
-  ethtool -K "${interface}" rx-udp-gro-forwarding on rx-gro-list off
-done
-
 # Default options
 options+=(--hostname "$(bashio::info.hostname)")
 
@@ -123,6 +109,21 @@ do
 done
 
 bashio::log.info "Tailscale is running"
+
+# Linux optimizations for subnet routers and exit nodes
+# Based on: https://tailscale.com/kb/1320/performance-best-practices#linux-optimizations-for-subnet-routers-and-exit-nodes
+# Note: Changes made via ethtool are not persistent and will be lost after the machine shuts down
+if interface=$( \
+  curl -sf --unix-socket /var/run/tailscale/tailscaled.sock http://local-tailscaled.sock/localapi/v0/check-udp-gro-forwarding \
+  | jq -rc '.Warning' \
+  | sed -nr 's/^UDP GRO forwarding is suboptimally configured on (\S+),.*$/\1/p') \
+  && bashio::var.has_value "${interface}";
+then
+  bashio::log.info "Enabling UDP GRO for forwarding on ${interface}"
+  if ! ethtool -K "${interface}" rx-udp-gro-forwarding on rx-gro-list off; then
+    bashio::log.warning "Enabling UDP GRO failed"
+  fi
+fi
 
 # Delete previously created persistent tailscale serve configuration ONCE
 # After add-on's serve (proxy and funnel) service is a longrun service, we do not modify the serve state permanently
